### ISSUE TITLE
Upgrade from 0.63.0 to 0.67.0

### ISSUE THREAD

**Issue by mroth** [boxen/puppet-foreman#4]
Foreman recently got a slew of updates after a year of being idle:
https://github.com/ddollar/foreman/blob/master/Changelog.md

I would send a PR to upgrade this but it looks like this module is using a hardcoded vendored binary installed on GitHub's S3 instance, so it will require someone with special permissions to update:
https://github.com/boxen/puppet-foreman/blob/0f762f4f6d849e4bcdfcb9c2e2feb92bae24504a/manifests/init.pp#L17

From that, two questions:
1. Is the vendored mirror necessary, or can we switch to using the official download, so repackaging is not necessary every time there is an update? (It looks like the binary download is now provided via .pkg file on assets.foreman.io)
2. If the vendored mirror is necessary, can someone with appropriate permissions update?

**Comment by jacobbednarz** [comment]
We're getting rid of the S3 downloads so the offical is :ok_hand:
