### ISSUE TITLE
Document what puppet-forman is

### ISSUE THREAD

**Issue by spuder** [boxen/puppet-foreman#5]
There is no link to what puppet-forman is. Even looking at the source and the travis builds, it is still impossible to tell what is going to be installed. 

Add a link to the software page and a description of what foreman is.

**Comment by dgoodlad** [comment]
@spuder I'd be very happy to accept a PR for this

**Comment by spuder** [comment]
I'd be happy to, however even after downloading foreman from http://boxen-downloads.s3.amazonaws.com/foreman/foreman-0.63.0.github1.tgz and looking through all the files. I myself can't figure out what foreman is supposed to do.  Is it a program? Is it a library? Is it a virus?

After googling, my best guess is that it installs this project http://theforeman.org/

**Comment by dgoodlad** [comment]
@spuder it's https://github.com/ddollar/foreman
